<?php

use Illuminate\Foundation\Inspiring;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Storage;

Artisan::command('inspire', function () {
    $this->comment(Inspiring::quote());
})->purpose('Display an inspiring quote');

Artisan::command('mock:assets {--images=200} {--rows=10000}', function () {
    $imageCount = (int) $this->option('images');
    $rowCount = (int) $this->option('rows');

    $baseDir = 'mock';
    $imagesDir = $baseDir . '/images';
    Storage::disk('local')->deleteDirectory($baseDir);
    Storage::disk('local')->makeDirectory($imagesDir);

    $createImage = function (string $path, int $width, int $height): void {
        $image = imagecreatetruecolor($width, $height);
        $background = imagecolorallocate($image, random_int(150, 255), random_int(150, 255), random_int(150, 255));
        imagefilledrectangle($image, 0, 0, $width, $height, $background);
        $textColor = imagecolorallocate($image, 70, 70, 70);
        imagestring($image, 5, 10, 10, basename($path), $textColor);
        imagejpeg($image, $path, 85);
        imagedestroy($image);
    };

    $this->info("Generating {$imageCount} placeholder images…");
    for ($i = 1; $i <= $imageCount; $i++) {
        $filename = sprintf('image_%04d.jpg', $i);
        $createImage(
            storage_path('app/' . $imagesDir . '/' . $filename),
            800 + random_int(0, 400),
            600 + random_int(0, 400)
        );
    }

    $csvPath = storage_path('app/' . $baseDir . '/products.csv');
    $this->info("Generating CSV with {$rowCount} rows at {$csvPath}");
    $handle = fopen($csvPath, 'w');
    fputcsv($handle, ['sku', 'name', 'price', 'description', 'upload_id']);

    for ($i = 1; $i <= $rowCount; $i++) {
        $sku = 'SKU' . str_pad((string) $i, 6, '0', STR_PAD_LEFT);
        $name = 'Product ' . $i;
        $price = number_format(random_int(1000, 50000) / 100, 2, '.', '');
        $description = 'Autogenerated product #' . $i;
        $placeholderUpload = 'PENDING_UPLOAD_ID';
        fputcsv($handle, [$sku, $name, $price, $description, $placeholderUpload]);
    }

    fclose($handle);

    $this->info('Mock assets created. Update the upload_id column after running chunked uploads.');
})->purpose('Generate mock CSV data (≥10k rows) and placeholder images for testing.');